In [2]:
import numpy as np

### Задание 1

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [5]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [6]:
spam1 = a_centered[:, 0]
spam2 = a_centered[:, 1]
a_centered_sp = np.dot(spam1, spam2)
a_centered_sp

8.0

In [7]:
N = a.shape[0]
N

5

In [8]:
my_cov = a_centered_sp / (N - 1)
my_cov

2.0