In [1]:
import numpy as np

### Задание 1

In [2]:
a = np.arange(12, 24)

### Задание 2

In [3]:
a1 =a.reshape(2, 6)
a2 =a.reshape(3, 4)
a3 =a.reshape(4, 3)
a4 =a.reshape(6, 2)
a5 =a.reshape(12, 1)
print(f'{a1}\n\n{a2} \n\n{a3} \n\n{a4}\n\n{a5}')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 3

In [4]:
a1 =a.reshape(-1, 6)
a2 =a.reshape(-1, 4)
a3 =a.reshape(-1, 3)
a4 =a.reshape(6, -1)
a5 =a.reshape(12, -1)
print(f'{a1}\n\n{a2} \n\n{a3} \n\n{a4}\n\n{a5}')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 4. 
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?<br />
Нет, так как  shape возвращает кортеж из 2 элементов

### Задание 5

In [5]:
b = np.random.randn(3, 4)
b1 = b.flatten()
print(f'{b}\n\n{b1}\n\n{b.size, b1.size}')

[[ 1.43317274 -0.70935264  0.21110173  1.56126579]
 [-0.98708663 -0.83158525 -0.28458259 -0.5563124 ]
 [ 0.29921862 -0.93060055  0.35790505  0.58321654]]

[ 1.43317274 -0.70935264  0.21110173  1.56126579 -0.98708663 -0.83158525
 -0.28458259 -0.5563124   0.29921862 -0.93060055  0.35790505  0.58321654]

(12, 12)


### Задание 6

In [6]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

In [7]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Разница между a и b в том, что массив a - одномерный, а b - многомерный.

### Задание 8

In [8]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(f'{c}\n\n{c.size}')

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

10


### Задание 9

In [9]:
a = np.arange(12)
A =a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
At = np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [11]:
B = A@At
print(f'{B}\n\n{B.size}')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

16


Матрица В не квадратная, соответвенно ее определитель равен 0. Обратную матрицу можно посчитать только для матрицы,
определитель которой не равен 0.

### Задание 10

In [12]:
np.random.seed(42)

### Задание 11

In [13]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание 12

In [14]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [15]:
D = B + (C * 10)
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [16]:
D_inv = np.linalg.inv(D)
print(f'Определитель = {np.linalg.det(D)},\nранг = {np.linalg.matrix_rank(D)}\nобратная матрица:\n{D_inv}')

Определитель = -28511999.999999944,
ранг = 4
обратная матрица:
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


### Задание 13

In [17]:
D_inv=np.where([D_inv < 0], 0, 1)
D_inv

array([[[1, 1, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 1, 0]]])

In [18]:
E = np.where([D_inv == 1], B, C)
E

array([[[[  5,  14,  23,  14],
         [ 10,   7,  12, 122],
         [  6,   9,   2, 212],
         [ 32,  10, 212,   4]]]])